openapi: 3.0.0
info:
  title: To-Do List API
  description: API untuk manajemen To-Do List
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /todos:
    get:
      summary: Mendapatkan semua daftar To-Do
      description: Mengambil daftar semua tugas dalam To-Do List
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    task:
                      type: string
                    completed:
                      type: boolean
    post:
      summary: Menambahkan tugas baru ke To-Do List
      description: Menambahkan tugas baru ke To-Do List
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: Nama tugas yang akan ditambahkan
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID dari tugas yang ditambahkan
                  task:
                    type: string
                    description: Nama tugas yang ditambahkan
                  completed:
                    type: boolean
                    description: Status tugas yang ditambahkan
  '/todos/{todoId}':
    get:
      summary: Mendapatkan detail tugas To-Do berdasarkan ID
      description: Mengambil detail tugas To-Do berdasarkan ID yang diberikan
      parameters:
        - name: todoId
          in: path
          description: ID dari tugas yang ingin dilihat
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  task:
                    type: string
                  completed:
                    type: boolean
    put:
      summary: Memperbarui tugas To-Do berdasarkan ID
      description: Memperbarui tugas To-Do berdasarkan ID yang diberikan
      parameters:
        - name: todoId
          in: path
          description: ID dari tugas yang ingin diperbarui
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                  description: Nama tugas yang diperbarui
                completed:
                  type: boolean
                  description: Status tugas yang diperbarui
      responses:
        '200':
          description: OK
    delete:
      summary: Menghapus tugas To-Do berdasarkan ID
      description: Menghapus tugas To-Do berdasarkan ID yang diberikan
      parameters:
        - name: todoId
          in: path
          description: ID dari tugas yang ingin dihapus
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content